name: flamingzipper
description: Flaming Zipper
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/logo_small.png
    - images/logo_dark.png
    - images/logo_dark_small.png
    - google_fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: google_fonts/NotoSansJP-Regular.otf
