name: flamingzipper
description: Flaming Zipper
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_native_splash: ^2.2.4
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  cloud_functions: ^3.3.2
  firebase_storage: ^10.3.2
  equatable: ^2.0.3
  go_router: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/logo_small.png
    - images/logo_dark.png
    - images/logo_dark_small.png
    - google_fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: google_fonts/NotoSansJP-Regular.otf
