name: Deploy to Firebase Functions and Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache functions/node_modules
        uses: actions/cache@v2
        id: cache-functions-node_modules
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-${{ hashFiles('functions/package-lock.json') }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # - name: Cache flutter
      #   uses: actions/cache@v2
      #   id: cache-flutter
      #   with:
      #     path: ${{ runner.tool_cache }}/flutter
      #     key: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      # - name: Cache flutter packages
      #   uses: actions/cache@v2
      #   id: cache-flutter-packages
      #   with:
      #     path: /home/runner/.pub-cache
      #     key: ${{ runner.os }}-${{ hashFiles('pubspec.lock') }}

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - run: npm ci && cd functions && npm ci
      - run: npm test
      - name: Deploy backends
        run: |
          npm run deploy:backend -- \
            --token "${{ secrets.FIREBASE_TOKEN_FLAMINGZIPPER }}"

      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLAMINGZIPPER }}'
      #     channelId: live
      #     projectId: flamingzipper

      - name: Deploy data
        run: |
          npm run deploy:data -- \
            --token "${{ secrets.FIREBASE_TOKEN_FLAMINGZIPPER }}"
